version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React app...
      - npm run build 
artifacts:
  files:
    - '**/*'
  base-directory: build 
cache:
  paths:
    - node_modules/**/*

